# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Robik - El robot imprimible que puede mover el cubo de Rubik
email: robik@recunchomaker.com
description: > # this means to ignore newlines until "baseurl:"
  Robik es un pequeno robot imprimible open hardware basado
  en Arduino que puede mover el cubo de rubik a traves de
  comandos por el puerto serie. 
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://recunchomaker.org/robik" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
